/*  Run each block in order (1, then 2, then 3 etc), comment out each block after you run the code
(so only the block you are running is not commented out) */


/*  1  */
/* 
ALTER TABLE APPLICANTS DROP CONSTRAINT FK_APPLICANTS_ADDRESS_ID;
ALTER TABLE APPLICANTS DROP CONSTRAINT FK_APPLICANTS_UNI_ID;
ALTER TABLE APPLICANTS DROP CONSTRAINT FK_APPLICANTS_TALENT_COORDINATOR_ID;
*/

/*  2  */
/* 
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS UNI;
DROP TABLE IF EXISTS TALENT_COORDINATORS;
DROP TABLE IF EXISTS APPLICANTS;
*/

/*  3  */
/* 
CREATE TABLE ADDRESS (
    ADDRESS_ID INT IDENTITY(1,1) PRIMARY KEY,
    ADDRESS_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE UNI (
    UNI_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);
CREATE TABLE TALENT_COORDINATORS (
    TALENT_COORDINATOR_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);
CREATE TABLE APPLICANTS (
    APPLICANT_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ADDRESS_ID INT,
    UNI_ID INT,
    DEGREE_GRADE VARCHAR(50),
    TALENT_COORDINATOR_ID INT,
    PHONE_NUMBER VARCHAR(255),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    FOREIGN KEY (UNI_ID) REFERENCES UNI(UNI_ID),
    FOREIGN KEY (TALENT_COORDINATOR_ID) REFERENCES TALENT_COORDINATORS(TALENT_COORDINATOR_ID)
);  
*/


/* 
*/

/*  4  */
/* 
UPDATE Talent_CSV 
SET address = 'Address Is Unknown' 
WHERE address IS NULL;

INSERT INTO ADDRESS (ADDRESS_NAME) 
SELECT DISTINCT address 
FROM Talent_CSV;


UPDATE Talent_CSV 
SET uni = 'University Is Unknown' 
WHERE uni IS NULL;

INSERT INTO UNI (NAME) 
SELECT DISTINCT uni 
FROM Talent_CSV;

UPDATE Talent_CSV 
SET invited_by = 'Talent Coordinator Unknown' 
WHERE invited_by IS NULL;

INSERT INTO TALENT_COORDINATORS (NAME) 
SELECT DISTINCT invited_by
FROM Talent_CSV
WHERE invited_by NOT IN (SELECT NAME FROM TALENT_COORDINATORS);


INSERT INTO APPLICANTS (NAME, DOB, EMAIL, ADDRESS_ID, UNI_ID, DEGREE_GRADE, TALENT_COORDINATOR_ID)
SELECT 
    t.name, 
    ISNULL(t.dob, '1900-01-01') AS DOB,
    ISNULL(t.email, 'Unknown') AS EMAIL,
    a.ADDRESS_ID, 
    u.UNI_ID, 
    t.degree, 
    tc.TALENT_COORDINATOR_ID
    t.phone_number 
FROM 
    Talent_CSV t
JOIN 
    ADDRESS a ON t.address = a.ADDRESS_NAME
JOIN 
    UNI u ON t.uni = u.NAME
JOIN 
    TALENT_COORDINATORS tc ON t.invited_by = tc.NAME;

*/

/*
SELECT * FROM APPLICANTS;
SELECT * FROM ADDRESS;
SELECT * FROM UNI;
SELECT * FROM TALENT_COORDINATORS;
*/

/*

*/

SELECT * FROM APPLICANTS;
SELECT * FROM ADDRESS;
SELECT * FROM UNI;
SELECT * FROM TALENT_COORDINATORS;