/*  Run each block in order (1, then 2, then 3 etc), comment out each block after you run the code
(so only the block you are running is not commented out) */


/*               */

/*              

DROP TABLE IF EXISTS WEAKNESSES;


DROP TABLE IF EXISTS STRENGTHS;

*/

/*   
CREATE TABLE WEAKNESSES (
    WEAKNESS_ID INT PRIMARY KEY,
    WEAKNESS_NAME VARCHAR NOT NULL
);


CREATE TABLE STRENGTHS (
    STRENGTH_ID INT PRIMARY KEY,
    STRENGTH_NAME VARCHAR NOT NULL
);


CREATE TABLE WEAKNESS_JUNCTION (
    APPLICANT_ID INT,
    WEAKNESS_ID INT,
    FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANTS(APPLICANT_ID),
    FOREIGN KEY (WEAKNESS_ID) REFERENCES WEAKNESSES(WEAKNESS_ID),
    PRIMARY KEY (APPLICANT_ID, WEAKNESS_ID)
);

CREATE TABLE STRENGTH_JUNCTION (
    APPLICANT_ID INT,
    STRENGTH_ID INT,
    FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANTS(APPLICANT_ID),
    FOREIGN KEY (STRENGTH_ID) REFERENCES STRENGTHS(STRENGTH_ID),
    PRIMARY KEY (APPLICANT_ID, STRENGTH_ID)
);

*/
